//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LommeradarenWeb.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int PictureID { get; set; }
        public int UserUserID { get; set; }
        public int PointOfInterestPOI_ID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public byte[] Picture { get; set; }
        public string PictureName { get; set; }
        public string FileName { get; set; }
    
        public virtual PointOfInterest PointOfInterest { get; set; }
        public virtual Users Users { get; set; }
    }
}
