//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LommeradarenWeb.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfInterest
    {
        public PointOfInterest()
        {
            this.Picture = new HashSet<Picture>();
        }
    
        public int POI_ID { get; set; }
        public string name { get; set; }
        public string imo { get; set; }
        public string mmsi { get; set; }
        public string webpage { get; set; }
    
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
